apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/mongo
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/redis
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-kafka-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/kafka
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-minio-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/minio/config
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-minio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/minio/data
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/prometheus
    server: 192.168.101.7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openim-grafana-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /k8s/openim/grafana
    server: 192.168.101.7
